import { prisma } from "@/lib/prisma";
let bad = 0;
const eq = (l: string, a: unknown, b: unknown) => { const s = String(a) === String(b); console.log(`${s ? "✅" : "❌"} ${l}：${a} / 预期 ${b}`); if (!s) bad++; };
const old = await prisma.saleOrder.findUnique({ where: { id: 20037 } });
const neu = await prisma.saleOrder.findFirst({ where: { revisionOf: 20037 }, include: { items: true } });
eq("旧版：已作废（revise 自动作废旧版，避免两版同时生效）", old!.status, "voided");
eq("旧版：保留为已驳回，不删除", old!.reviewStatus, "rejected");
eq("新版：血缘指向旧版", neu!.revisionOf, 20037);
eq("新版：version 递增", neu!.version, 2);
eq("新版：数量已按意见改成 3", Number(neu!.items[0].quantity).toFixed(3), "3.000");
eq("新版：仍是 Agent 建的、待审核", `${neu!.actorKind}/${neu!.reviewStatus}`, "agent/pending_review");
eq("新版：记的是新批次的 runId", neu!.agentRunId, "run-20260914-demo2");
// 通过之后
const approved = await prisma.saleOrder.findUnique({ where: { id: neu!.id } });
const p = await prisma.product.findUnique({ where: { id: 1185 }, select: { stockQty: true, stockAmount: true, avgCost: true } });
console.log(`  新版审核状态=${approved!.reviewStatus} reviewedBy=${approved!.reviewedBy}`);
console.log(`  商品库存=${p!.stockQty}（30 起 → 旧版卖 5 → 作废回补 +5=30 → 新版卖 3 → 27）`);
eq("库存最终 = 27", Number(p!.stockQty).toFixed(3), "27.000");
eq("均价保持 10", Number(p!.avgCost).toFixed(4), "10.0000");
const notes = await prisma.reviewNote.findMany({ where: { docId: 20037 }, orderBy: { id: "asc" } });
eq("旧版意见留痕（1 轮）", notes.length, 1);
const notes2 = await prisma.reviewNote.findMany({ where: { docId: neu!.id } });
eq("新版意见留痕（通过）", notes2.length >= 1, true);
console.log(bad === 0 ? "\n审核闭环验收通过" : `\n${bad} 项不一致`);
process.exitCode = bad === 0 ? 0 : 1;
await prisma.$disconnect();
