import { prisma } from "@/lib/prisma";
let bad = 0;
const eq = (l: string, a: unknown, b: unknown) => { const s = String(a) === String(b); console.log(`${s ? "✅" : "❌"} ${l}：${a} / 预期 ${b}`); if (!s) bad++; };
const rets = await prisma.purchaseReturn.findMany({ where: { purchaseOrderId: { in: [28, 29] } }, orderBy: { id: "asc" } });
eq("同一天两张退货单，单号递增", rets.map((r) => r.orderNo).join(","), "PRF20260914-0001,PRF20260914-0002");
const p = await prisma.product.findUnique({ where: { id: 1181 }, select: { stockQty: true, stockAmount: true, avgCost: true } });
eq("库存 150 → 100（退 30+20）", Number(p!.stockQty).toFixed(3), "100.000");
eq("金额 2900 → 1935（按当前均价 19.3333 出库：50×19.33=966.67 取 966.5？）", Number(p!.stockAmount).toFixed(2), "1935.00");
eq("均价保持 19.3333（按当前均价出库不改变均价）", Number(p!.avgCost).toFixed(4), "19.3333");
const mv = await prisma.stockMovement.findMany({ where: { productId: 1181, bizType: "purchase_return_out" }, orderBy: { id: "asc" } });
eq("两条出库流水，单价都是当时均价", mv.map((m) => `${Number(m.changeQty)}@${Number(m.unitCost)}`).join(","), "-30@19.3333,-20@19.3333");
const a = await prisma.auditLog.findMany({ where: { entityType: "purchase_return", action: "create", ip: "cli" }, orderBy: { id: "desc" }, take: 2 });
eq("两条审计都带来源", a.every((x) => (x.afterJson as {source?:string}).source === "cli:进货退货验收"), true);
console.log(bad === 0 ? "\n进货退货验收通过（含 P0-2 场景）" : `\n${bad} 项不一致`);
process.exitCode = bad === 0 ? 0 : 1;
await prisma.$disconnect();
